services:
    mariadb:
        image: mariadb:lts
        container_name: mariadb
        environment:
            MARIADB_DATABASE: testing_db
            MARIADB_USER:    laravel
            MARIADB_PASSWORD: password
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
            - ./docker/mariadb/config:/etc/mysql
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 10s
            timeout:  5s
            retries:  5
        networks:
            - static-network

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - static-network
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: api-testing
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        ports:
            - "801:80"
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            DB_HOST:     mariadb
            DB_PORT:     3306
            DB_DATABASE: testing_db
            DB_USERNAME: laravel
            DB_PASSWORD: password
        depends_on:
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - static-network

networks:
    static-network:
        driver: bridge
